# Generated by Django 6.0.7 on 2026-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArtculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdf', models.CharField(max_length=100)),
                ('Artculture_title', models.TextField()),
                ('img_Technology', models.ImageField(upload_to='images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('img_Decoration', models.ImageField(upload_to='images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begtxt', models.CharField(max_length=100)),
                ('longtitle', models.TextField()),
                ('img_Lifestyle', models.ImageField(upload_to='images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Newsoftheday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_news', models.CharField(max_length=100)),
                ('title_news', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('img_ftheday', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('img_Technology', models.ImageField(upload_to='images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
