# Generated by Django 6.0.7 on 2026-07-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsartculture',
            name='img_Technology',
        ),
        migrations.AlterField(
            model_name='newsartculture',
            name='Artculture_title',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
