# Generated by Django 6.0.7 on 2026-07-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_remove_newsartculture_img_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsartculture',
            name='img_Artculture',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsartculture',
            name='Artculture_title',
            field=models.TextField(),
        ),
    ]
