# Generated by Django 6.0.7 on 2026-07-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_newsartculture_img_artculture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsartculture',
            old_name='fdf',
            new_name='dodslg',
        ),
    ]
