# Generated by Django 6.0.7 on 2026-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_rename_fdf_newsartculture_dodslg'),
    ]

    operations = [
        migrations.CreateModel(
            name='slidertxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_slider', models.CharField(max_length=200)),
            ],
        ),
    ]
