# Generated by Django 6.0.7 on 2026-07-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_slidertxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slidernews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Typenews', models.CharField(max_length=30)),
                ('category_tag', models.CharField(max_length=100)),
                ('display_title', models.TextField()),
                ('slider_image', models.ImageField(upload_to='images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
