# Generated by Django 6.0.7 on 2026-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_slidernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsartculture',
            name='page_newsArtculture_title',
            field=models.TextField(default='یوخدی'),
        ),
        migrations.AddField(
            model_name='newsartculture',
            name='pagetxt_newsArtculture',
            field=models.CharField(default='یوخدی', max_length=100),
        ),
        migrations.AddField(
            model_name='newsdecoration',
            name='page_newsDecoration_title',
            field=models.TextField(default='یوخدی'),
        ),
        migrations.AddField(
            model_name='newsdecoration',
            name='pagetxt_newsDecoration',
            field=models.CharField(default='یوخدی', max_length=100),
        ),
        migrations.AddField(
            model_name='newslifestyle',
            name='page_newsLifestyle_title',
            field=models.TextField(default='یوخدی'),
        ),
        migrations.AddField(
            model_name='newslifestyle',
            name='pagetxt_newsLifestyle',
            field=models.CharField(default='یوخدی', max_length=100),
        ),
        migrations.AddField(
            model_name='newsoftheday',
            name='page_newsoftheday_title',
            field=models.TextField(default='یوخدی'),
        ),
        migrations.AddField(
            model_name='newsoftheday',
            name='pagetxt_newsoftheday',
            field=models.CharField(default='یوخدی', max_length=100),
        ),
        migrations.AddField(
            model_name='newstechnology',
            name='page_newsTechnology_title',
            field=models.TextField(default='یوخدی'),
        ),
        migrations.AddField(
            model_name='newstechnology',
            name='pagetxt_newsTechnology',
            field=models.CharField(default='یوخدی', max_length=100),
        ),
    ]
