# Generated by Django 6.0.7 on 2026-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_newsartculture_page_newsartculture_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_usernameandlastname', models.CharField(max_length=50)),
                ('coment_title', models.CharField(max_length=300)),
                ('imguser', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
