# Generated by Django 6.0.7 on 2026-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='coment',
            name='news_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coment',
            name='coment_title',
            field=models.CharField(max_length=300, verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='coment_usernameandlastname',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='imguser',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر کاربر'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
