# Generated by Django 6.0.7 on 2026-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_pagevideo_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_portfolio', models.CharField(max_length=100)),
                ('ttile_portfolio', models.TextField()),
                ('img_portfolio', models.ImageField(upload_to='images/')),
                ('file_portfoli', models.FileField(upload_to='')),
            ],
        ),
    ]
