# Generated by Django 6.0.7 on 2026-08-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidernews',
            name='page_slidernews_title',
            field=models.TextField(default='یوخدی'),
        ),
        migrations.AddField(
            model_name='slidernews',
            name='pagetxt_slidernews',
            field=models.CharField(default='یوخدی', max_length=100),
        ),
    ]
